/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#f0e5eb",
        "on-primary": "#ffffff",
        "surface-container-highest": "#eae0e5",
        "on-background": "#1f1a1e",
        "outline": "#80737d",
        "on-tertiary-fixed-variant": "#404b17",
        "tertiary-fixed-dim": "#bfcd8b",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d9e3f9",
        "secondary-fixed-dim": "#bdc7dc",
        "inverse-surface": "#352f33",
        "on-secondary-fixed": "#121c2c",
        "on-primary-fixed": "#370139",
        "surface-tint": "#844981",
        "primary-fixed": "#ffd6f8",
        "surface-bright": "#fff7fa",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f9eef3",
        "surface-variant": "#eae0e5",
        "on-secondary-container": "#596376",
        "tertiary": "#141a00",
        "inverse-primary": "#f6afef",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3d4759",
        "on-tertiary-fixed": "#171e00",
        "on-tertiary": "#ffffff",
        "surface-container": "#f6ebf0",
        "on-primary-fixed-variant": "#693168",
        "outline-variant": "#d2c2cd",
        "surface-container-low": "#fcf1f6",
        "on-surface-variant": "#4f434c",
        "background": "#fff7fa",
        "on-primary-container": "#be7db9",
        "primary": "#300033",
        "surface": "#fff7fa",
        "primary-fixed-dim": "#f6afef",
        "secondary-container": "#d6e0f6",
        "tertiary-container": "#263000",
        "secondary": "#555f71",
        "surface-dim": "#e2d7dd",
        "on-surface": "#1f1a1e",
        "primary-container": "#4a154b",
        "on-tertiary-container": "#8c995d",
        "tertiary-fixed": "#dbe9a5",
        brand: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2c0b61',
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "32px",
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "gutter": "24px",
        "base": "4px",
        "max-width": "1440px",
        "lg": "24px",
        "xl": "40px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "title-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
